In [2]:
import numpy as np

# Ders 1

In [2]:
x = np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
y = np.array(["a","b","c"])

In [5]:
y

array(['a', 'b', 'c'], dtype='<U1')

# Ders 2

In [7]:
x = np.array([1,2,3,4.5])

In [8]:
x

array([1. , 2. , 3. , 4.5])

In [9]:
x = np.array([1,2,3,4.5], dtype="int32")

In [10]:
x

array([1, 2, 3, 4], dtype=int32)

In [11]:
x = np.array([1,2,3,4.5], dtype="str")

In [12]:
x

array(['1', '2', '3', '4.5'], dtype='<U3')

In [14]:
x = np.array(["5"], dtype="int32")

In [15]:
x

array([5], dtype=int32)

In [17]:
x=np.array(["4.2"],dtype="float")

In [18]:
x

array([4.2])

# Ders 3

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros(10, dtype="str")

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [22]:
np.zeros(10, dtype="bool")

array([False, False, False, False, False, False, False, False, False,
       False])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros([3,4,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Ders 4

In [30]:
np.full([3,3],1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
np.full((4,4),5,dtype="int")

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [38]:
np.full(3,5)

array([5, 5, 5])

# Ders 5

In [44]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [45]:
np.arange(7,21)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
np.arange(10,20,4.4)

array([10. , 14.4, 18.8])

In [47]:
np.arange(22,2,-5)

array([22, 17, 12,  7])

# Ders 6

In [49]:
np.linspace(1,2) #Default olarak 50 parçaya böler

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [50]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [52]:
np.linspace(1,2,3,endpoint=False)

array([1.        , 1.33333333, 1.66666667])

In [53]:
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [55]:
np.linspace(1.2,7.2,10)

array([1.2       , 1.86666667, 2.53333333, 3.2       , 3.86666667,
       4.53333333, 5.2       , 5.86666667, 6.53333333, 7.2       ])

# Ders 7

In [56]:
np.random.normal(0,1,(3,3))

array([[-1.38155969,  0.21697495, -1.77877668],
       [-1.72759584, -1.04768704, -0.28035848],
       [-0.28258876, -1.01454676, -0.0737893 ]])

In [64]:
np.random.normal(0,0.5,(3,3))

array([[-0.12568164,  0.28283498, -0.08249105],
       [-0.72747415,  0.51989247,  0.30914343],
       [ 0.79140882, -1.42845844, -0.00320338]])

# Ders 8

In [74]:
np.random.randint(0, 10, (3, 3))

array([[3, 0, 9],
       [5, 5, 3],
       [2, 8, 9]])

In [98]:
np.random.randint(0,10)

9

In [107]:
d = {}

for _ in range(20000):
    val = np.random.randint(1,11)
    
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1
    

In [108]:
d

{8: 2015,
 1: 1987,
 4: 1973,
 10: 2008,
 5: 1990,
 2: 1997,
 6: 1965,
 7: 1996,
 9: 2045,
 3: 2024}

# Ders 9 

In [109]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [111]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Ders 10

In [112]:
x = np.array([2,4,8])
y = np.array([1,2,3])

In [113]:
x*y

array([ 2,  8, 24])

In [114]:
x + y

array([ 3,  6, 11])

In [115]:
3*x

array([ 6, 12, 24])

In [116]:
x = x * 3

In [117]:
x

array([ 6, 12, 24])

# Ders 11

In [125]:
x = np.zeros([2,3])
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [124]:
y = np.zeros([2,5,4])
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [122]:
x.shape

(2, 3)

In [123]:
y.shape

(2, 5, 4)

In [126]:
x.ndim

2

In [127]:
y.ndim

3

In [128]:
x.size

6

In [129]:
y.size

40

In [130]:
x.dtype

dtype('float64')

In [131]:
y.dtype

dtype('float64')

# Ders 12

In [134]:
a = np.arange(1,11)

In [135]:
a.ndim

1

In [136]:
a.size

10

In [138]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [139]:
a.reshape(2,5).ndim

2

In [144]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [145]:
a[np.newaxis, : ]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [147]:
a[np.newaxis, : ].shape

(1, 10)

# Ders 13

In [148]:
a = np.arange(1,5)

In [149]:
b = np.arange(5,10)

In [150]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
l = [10,11]

In [152]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Ders 14 

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([5,6,7,8])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
b

array([5, 6, 7, 8])

In [7]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
np.stack([a,b], axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Ders 15

In [11]:
l = [10,20,30,40,50,60,70,80,90]

In [12]:
l

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [13]:
np.split(l,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80, 90])]

In [14]:
a,b = (1,10)

In [16]:
x,y,z = np.split(l, [2,7])

In [17]:
x

array([10, 20])

In [18]:
y

array([30, 40, 50, 60, 70])

In [19]:
z

array([80, 90])

In [22]:
a = np.arange(20).reshape(-1,10)

In [23]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [27]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [29]:
np.hsplit(a,[2,7])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16]]),
 array([[ 7,  8,  9],
        [17, 18, 19]])]

In [30]:
a=np.arange(20).reshape(5,4) 

In [31]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Ders 16

In [38]:
a = np.array([20,12,17,35,4])

In [39]:
np.sort(a)

array([ 4, 12, 17, 20, 35])

In [36]:
a.sort() # a = np.sort(a) ile aynı şey günceller değeri xd

In [35]:
a

array([ 4, 12, 17, 20, 35])

In [41]:
np.argsort(a) # indexleri döndürür

array([4, 1, 2, 0, 3])

# Ders 17

In [44]:
a = np.arange(1,21).reshape(-1,5)

In [45]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
a[0]

array([1, 2, 3, 4, 5])

In [47]:
a[0][0]

1

In [53]:
a[3,4]

20

In [57]:
a[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [58]:
a[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [59]:
a[:,3]

array([ 4,  9, 14, 19])

In [60]:
a[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [61]:
a[::,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [62]:
a=np.arange(1,13).reshape(3,4) 

In [63]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Ders 18

In [65]:
x = np.arange(1,15)

In [66]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
idxs = [3,6,9,12]

In [68]:
x[idxs]

array([ 4,  7, 10, 13])

In [83]:
a = np.arange(20).reshape(-1,5)

In [84]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
a[:2,1]

array([1, 5])

In [75]:
a[:2,:1]

array([[0],
       [4]])

In [76]:
a[0, [1,3]]

array([1, 3])

In [86]:
idx1 = [1,3,2]
idx2 = [0,3,1]

In [87]:
a[idx1,idx2]

array([ 5, 18, 11])

In [88]:
a=np.arange(1,13).reshape(3,4) 

In [89]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Ders 19

In [90]:
a = np.arange(1,21).reshape(-1,5)

In [91]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [92]:
b = a[:2,:3]

In [93]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [94]:
b.shape

(2, 3)

In [95]:
b[0,0] = 100

In [96]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [97]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [101]:
b = a[:2,:3].copy()

In [102]:
b[0,0] = 1

In [103]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [104]:
b

array([[1, 2, 3],
       [6, 7, 8]])

# Ders 20

In [105]:
a = np.arange(20)

In [107]:
a[a<5]

array([0, 1, 2, 3, 4])

In [108]:
filt = a >12

In [109]:
a[filt]

array([13, 14, 15, 16, 17, 18, 19])

In [112]:
a[(a<3) |( a>8)]

array([ 0,  1,  2,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Ders 21

In [116]:
a = np.arange(1,21).reshape(-1,5)

In [117]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [118]:
np.sum(a)

210

In [119]:
filt = a < 5

In [120]:
np.sum(filt)

4

In [121]:
np.sum(a[filt])

10

In [122]:
filt = (a<10) | (a>17)

In [123]:
filt

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True]])

In [124]:
np.sum(filt)

12

In [125]:
np.sum(a[filt])

102

In [126]:
~filt

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False, False]])

In [127]:
np.sum(a,axis=0)

array([34, 38, 42, 46, 50])

In [129]:
np.sum(a,axis=1)

array([15, 40, 65, 90])

# Ders 22

In [130]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [131]:
np.all(a>5) # tümü sağlarsa true döenr

False

In [132]:
np.all(a>-1)

True

In [145]:
filt = a <12

In [146]:
filt

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [148]:
np.all(filt, axis=1)

array([ True,  True, False, False])

In [149]:
a=np.arange(1,21).reshape(4,5)

In [150]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [151]:
np.all(a>8,axis=1) 

array([False, False,  True,  True])

In [152]:
a>8

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Ders 23

In [153]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [155]:
np.any(a>18) # Herhangi biri doğruysa True döndürür

True